### ISSUE TITLE
运行时的问题

### ISSUE THREAD

**Issue by MiniTwist** [biezhi/lol-prophet#1]
在运行时，显示敌方信息时，会有一段错误信息在终端窗口。

**Comment by biezhi** [comment]
@MiniTwist 截图看哈呢

**Comment by MiniTwist** [comment]
为什么在运行最新版V1.0时，前几天还能打开设团置页面，现在都打不开了，http://localhost:4396/，提示：Not Found。@biezhi
![image](https://user-images.githubusercontent.com/106955924/173196667-21f88ddd-e74a-452b-bebb-daebd65df90e.png)

**Comment by biezhi** [comment]
![image](https://user-images.githubusercontent.com/43900052/173197091-cde6fec4-6693-412f-b2c8-864cdcbcb057.png)
![image](https://user-images.githubusercontent.com/43900052/173197146-783479ac-cc3b-456a-9084-696e7adb7df8.png)
那个程序文件目录结构应该是这样的，web存的是网页配置界面，检查下是否对的。运行是应该以管理员权限运行、然后有个防火墙提示点同意。
这个显示not found应该是前端界面没加载出来，试了还是不行重新下载试试。我本地没有出现那种情况，现在还在耍呢:smile:

**Comment by MiniTwist** [comment]
可以了，谢谢。
![Uploading image.png…]()
